In [3]:
#load libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn import datasets

In [8]:
#load dataset
X,y=datasets.load_diabetes(return_X_y=True)

In [14]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [12]:
y.shape

(442,)

In [15]:
#split test and train data
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)

In [16]:
#load model
rf=RandomForestClassifier(n_estimators=1000,random_state=42)

In [17]:
rf.fit(X_train,y_train)

RandomForestClassifier(n_estimators=1000, random_state=42)

In [18]:
y_pred=rf.predict(X_test)

In [20]:
confusion_matrix(y_test,y_pred)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [22]:
errors=(y_pred-y_test)

In [23]:
errors

array([   9.,  -84.,  -42.,  -31.,   80.,   23.,  -56.,  142., -114.,
        -18.,  134.,    8., -182.,  130.,  112., -148.,  -96.,   44.,
       -107.,    1.,  -43.,   -2.,   65., -134.,   36., -123.,   73.,
        -80.,   59.,   18.,   63.,   32.,  140.,  103.,  -26.,   13.,
        -43., -127.,    3.,   39.,  136., -100., -146.,   44.,   19.,
       -158.,    7.,  -52.,  -22.,  -22.,  -58.,  -17.,  117.,    6.,
        -61.,  -92.,  -46.,   16.,  -68.,   33.,  -58.,  -13., -104.,
        -29.,  -13.,  -57.,  -56.,  100.,  -24.,  -68.,   75.,  -41.,
       -166.,  213.,  -19.,   41.,  182.,   68.,  -30.,  -32.,  -56.,
       -105.,   83.,  -20.,  -24.,   -4.,   46.,   34.,    4.,   66.,
          5.,  167.,   -3.,   -6.,   18.,   20.,  -19.,  -54.,   82.,
         70.,  -20.,   75.,  -14.,   34.,  -25.,  -92.,    5.,   10.,
        -80.,  -10.,  -18.,   51.,  -13.,   44.,   56.,   79.,   19.,
         29.,  -35.,    3.,  -43.,   13.,   15.,  -36.,  -49.,   80.,
        107.,   37.,

In [24]:
# Calculate mean absolute percentage error (MAPE)
mape = 100 * (errors / y_test)

# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')

Accuracy: 84.16 %.
